import math

import pygame

from settings import (
    CELL_SIZE,
    BATTLEFIELD_TOP,
    BATTLEFIELD_LEFT,
)


class Enemy:
    """
    Represents an enemy controlled by the
    classical AI Commander.
    """

    def __init__(self, position, health=100, enemy_type="REGULAR"):
        self.row = float(position[0])
        self.col = float(position[1])

        self.max_health = health
        self.health = health

        self.damage = 10
        self.speed = 2.0
        self.slow_timer = 0.0
        self.ward_strength = 0.0
        self.state = "ADVANCING"
        self.escaped = False
        self.enemy_type = enemy_type
        self.attack_cooldown = 0.0
        self.walk_phase = 0.0
        self.gold_reward = 35 if enemy_type == "CAPTAIN" else 25
        self.score_reward = 40 if enemy_type == "CAPTAIN" else 20

        self.alive = True

        # A* path generated by the AI Commander.
        self.path = []
        self.path_index = 0

    @property
    def position(self):
        """
        Return the enemy's current grid position.

        The AI works with integer grid coordinates.
        """

        return (
            round(self.row),
            round(self.col)
        )

    def set_path(self, path):
        """
        Receive a path calculated by A*.
        """

        if not path:
            self.path = []
            self.path_index = 0
            return

        self.path = path
        self.path_index = 0

        # If the first point is the enemy's
        # current position, skip it.
        if (
            len(self.path) > 1
            and self.path[0] == self.position
        ):
            self.path_index = 1

    def clear_path(self):
        """
        Remove the current A* path.
        """

        self.path = []
        self.path_index = 0

    def update(self, delta_time):
        """
        Move the enemy along its A* path.
        """

        if not self.alive:
            return

        self.attack_cooldown = max(
            0.0,
            self.attack_cooldown - delta_time
        )

        if not self.path:
            return

        if self.path_index >= len(self.path):
            if self.state == "RETREATING":
                self.escaped = True
                self.alive = False
            else:
                self.state = "ATTACKING"
            return

        target_row, target_col = (
            self.path[self.path_index]
        )

        # Convert speed from pixels/second
        # into grid-cell movement.
        self.slow_timer = max(0.0, self.slow_timer - delta_time)
        speed_factor = 0.55 if self.slow_timer > 0 else 1.0
        retreat_factor = 1.3 if self.state == "RETREATING" else 1.0
        movement = self.speed * speed_factor * retreat_factor * delta_time
        self.walk_phase += delta_time * (12.0 if movement > 0 else 0.0)

        row_difference = (
            target_row - self.row
        )

        col_difference = (
            target_col - self.col
        )

        # Move vertically.
        if abs(row_difference) > 0.01:

            if row_difference > 0:
                self.row = min(
                    self.row + movement,
                    target_row
                )
            else:
                self.row = max(
                    self.row - movement,
                    target_row
                )

        # Move horizontally.
        elif abs(col_difference) > 0.01:

            if col_difference > 0:
                self.col = min(
                    self.col + movement,
                    target_col
                )
            else:
                self.col = max(
                    self.col - movement,
                    target_col
                )

        # Check whether the current waypoint
        # has been reached.
        if (
            abs(self.row - target_row) < 0.01
            and
            abs(self.col - target_col) < 0.01
        ):
            self.row = float(target_row)
            self.col = float(target_col)

            self.path_index += 1

            if self.path_index >= len(self.path):
                if self.state == "RETREATING":
                    self.escaped = True
                    self.alive = False
                else:
                    self.state = "ATTACKING"

    def has_reached_target(self):
        """
        Return True when the enemy has reached
        the end of its current A* path.
        """

        return (
            bool(self.path)
            and self.path_index >= len(self.path)
        )

    def take_damage(self, damage):
        """
        Apply damage to the enemy.
        """

        absorbed_damage = math.ceil(damage * self.ward_strength)
        damage_taken = damage - absorbed_damage
        if damage > 0:
            damage_taken = max(1, damage_taken)
        self.health -= damage_taken

        if self.health <= 0:
            self.health = 0
            self.alive = False

    def apply_slow(self, duration):
        self.slow_timer = max(self.slow_timer, duration)

    def draw(self, screen):
        """
        Draw the enemy.
        """

        center_x = round(
            BATTLEFIELD_LEFT + (self.col + 0.5) * CELL_SIZE
        )
        center_y = round(
            BATTLEFIELD_TOP + (self.row + 0.5) * CELL_SIZE
        )

        direction = self.facing_direction()
        angle = -math.degrees(math.atan2(direction.x, -direction.y))
        soldier = self.draw_soldier()
        soldier = pygame.transform.rotate(soldier, angle)
        screen.blit(soldier, soldier.get_rect(center=(center_x, center_y)))

        # Health bar.
        bar_width = CELL_SIZE - 20
        bar_height = 5

        health_ratio = (
            self.health
            / self.max_health
        )

        background_bar = pygame.Rect(
            center_x - bar_width // 2,
            center_y - 19,
            bar_width,
            bar_height
        )

        health_bar = background_bar.copy()
        health_bar.width = int(bar_width * max(0, health_ratio))

        if health_ratio > 0.6:
            health_color = (82, 203, 136)
        elif health_ratio > 0.3:
            health_color = (231, 183, 77)
        else:
            health_color = (222, 91, 77)

        pygame.draw.rect(
            screen,
            (38, 39, 42),
            background_bar,
            border_radius=3
        )

        pygame.draw.rect(
            screen,
            health_color,
            health_bar,
            border_radius=3
        )

        if self.slow_timer > 0:
            pygame.draw.circle(
                screen,
                (111, 203, 255),
                (center_x, center_y),
                17,
                1
            )
        if self.ward_strength > 0:
            pygame.draw.circle(
                screen,
                (114, 203, 255),
                (center_x, center_y),
                19,
                2
            )
            shield_badge = [
                (center_x + 12, center_y - 17),
                (center_x + 18, center_y - 14),
                (center_x + 17, center_y - 7),
                (center_x + 12, center_y - 3),
                (center_x + 7, center_y - 7),
                (center_x + 6, center_y - 14),
            ]
            pygame.draw.polygon(screen, (68, 128, 165), shield_badge)
            pygame.draw.polygon(screen, (190, 231, 255), shield_badge, 1)

    def facing_direction(self):
        if self.path_index < len(self.path):
            target_row, target_col = self.path[self.path_index]
            direction = pygame.Vector2(
                target_col - self.col,
                target_row - self.row
            )
            if direction.length_squared() > 0:
                return direction.normalize()
        return pygame.Vector2(1, 0)

    def draw_soldier(self):
        surface = pygame.Surface((CELL_SIZE, CELL_SIZE), pygame.SRCALPHA)
        center_x = CELL_SIZE // 2
        captain = self.enemy_type == "CAPTAIN"
        armor = (109, 44, 39) if not captain else (114, 83, 41)
        armor_light = (169, 69, 51) if not captain else (221, 171, 76)
        metal = (155, 165, 168)
        stride = round(math.sin(self.walk_phase) * 2)

        pygame.draw.ellipse(
            surface,
            (20, 23, 25, 150),
            pygame.Rect(5, 14, 30, 22)
        )

        # Boots and legs swing as the unit marches.
        pygame.draw.line(
            surface, (46, 43, 42),
            (center_x - 4, 23), (center_x - 5 - stride, 31), 5
        )
        pygame.draw.line(
            surface, (46, 43, 42),
            (center_x + 4, 23), (center_x + 5 + stride, 31), 5
        )
        pygame.draw.ellipse(
            surface, (33, 31, 30),
            pygame.Rect(center_x - 10 - stride, 28, 9, 5)
        )
        pygame.draw.ellipse(
            surface, (33, 31, 30),
            pygame.Rect(center_x + 1 + stride, 28, 9, 5)
        )

        # Arms, mail-covered torso and leather cross-belt.
        pygame.draw.line(
            surface, armor,
            (center_x - 7, 14), (center_x - 12, 22), 5
        )
        pygame.draw.line(
            surface, armor,
            (center_x + 7, 14), (center_x + 11, 21), 5
        )
        pygame.draw.ellipse(
            surface,
            (39, 42, 43),
            pygame.Rect(center_x - 9, 10, 18, 17)
        )
        pygame.draw.ellipse(
            surface,
            armor,
            pygame.Rect(center_x - 7, 11, 14, 14)
        )
        pygame.draw.line(
            surface, armor_light,
            (center_x - 5, 13), (center_x + 5, 22), 2
        )
        pygame.draw.circle(
            surface, metal, (center_x, 17), 2
        )

        # Shield and spear make troop facing and role readable at game scale.
        pygame.draw.ellipse(
            surface, (71, 48, 37),
            pygame.Rect(center_x + 7, 17, 8, 12)
        )
        pygame.draw.ellipse(
            surface, armor_light,
            pygame.Rect(center_x + 8, 18, 6, 9)
        )
        pygame.draw.line(
            surface, (111, 76, 49),
            (center_x - 8, 19), (center_x - 8, 3), 2
        )
        pygame.draw.polygon(
            surface,
            (194, 201, 195),
            [
                (center_x - 8, 1),
                (center_x - 11, 6),
                (center_x - 5, 6),
            ]
        )

        # Helmet, brow and plume.
        pygame.draw.circle(
            surface, (43, 46, 47),
            (center_x, 8), 7
        )
        pygame.draw.circle(
            surface, (132, 139, 139),
            (center_x, 7), 6
        )
        pygame.draw.arc(
            surface, (211, 215, 207),
            pygame.Rect(center_x - 5, 2, 10, 10),
            0.1, 3.0, 2
        )
        pygame.draw.line(
            surface, (79, 43, 35),
            (center_x - 5, 10), (center_x + 5, 10), 2
        )
        pygame.draw.line(
            surface, armor_light,
            (center_x, 2), (center_x, -2 if captain else 0), 2
        )
        if captain:
            pygame.draw.polygon(
                surface,
                (190, 50, 44),
                [
                    (center_x - 5, 13),
                    (center_x - 13, 25),
                    (center_x - 4, 22),
                    (center_x + 1, 29),
                    (center_x + 6, 20),
                ]
            )
            pygame.draw.line(
                surface,
                (235, 190, 106),
                (center_x, 3),
                (center_x, -1),
                3
            )
        return surface